# Generated by Django 4.1.5 on 2023-01-24 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 24, 8, 46, 1, 50822))),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.employees')),
            ],
        ),
    ]
